version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=antoniolegnante
      - POSTGRES_PASSWORD=lama
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"      # API
      - "9001:9001"      # Console Web UI
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: image_server
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: