version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=antoniolegnante
      - POSTGRES_PASSWORD=lama
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: image_server
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/usr/share/nginx/html/images
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  postgres_data: